const resume = {
  data: {
    honorifics: "Mohammed",
    firstName: "Salman",
    lastName: "Khan",
    photo: null,
    title: "Frontend Web Developer",
    location: "Dhaka, Bangladesh",
    phone: "+880 1305 335 088",
    email: "webdevz.sk@gmail.com",
    telephone: null,
    github: "https://github.com/webdevsk",
    linkedin: "https://linkedin.com/in/webdevsk",
    twitter: null,
    facebook: null,
    liveLink: "https://webdevsk.github.io/react-resume/",
    about:
      "I am a Frontend Web Developer creating interactable solutions and solving both technical and design challenges using Vanilla JavaScript and React JS. I have more than 2 years of experience in creating pixel-perfect and mobile responsive Websites that met client requirements. I debug design and functional issues with my deep knowledge on Dev Tools and Search Engines.",
    skills: [
      {
        heading: "Frontend",
        data: ["React", "JavaScript", "Tailwind", "Sass", "CSS", "HTML"],
      },
      {
        heading: "Backend",
        data: [
          "Express JS",
          "Node JS",
          "MongoDB",
          "MySQL",
          "Serverless",
          "Restful API",
        ],
      },
      {
        heading: "Technologies",
        data: ["Git", "GitHub", "WordPress", "Adobe Xd", "Figma"],
      },
    ],
    projects: [
      {
        title: "React TODO App",
        shortDescription: "A TODO APP built with React JS.",
        link: "https://celadon-cactus-42acbb.netlify.app/",
        repo: "https://github.com/webdevsk/react-todo-app",
        builtWith: [
          "React",
          "React-Router",
          "TailwindCSS",
          "Material-Tailwind",
        ],
        features: [
          "Create, mark, pin or delete tasks. Bulk check and remove completed tasks.",
          "Handheld device accessible. Bottom input field improves reachability.",
          "Create dynamic categories either from within the APP or from browser URL directly",
          "Side Menu visibility state is dynamically managed based on device orientation and viewport.",
        ],
      },
      {
        title: "Random Task Today",
        shortDescription:
          "Generate a random task to do today and see a refreshing photo related to it.",
        link: "https://splendid-narwhal-4770fd.netlify.app/",
        repo: "https://github.com/webdevsk/Random-task-today",
        builtWith: ["React", "TailwindCSS", "Netlify Serverless Functions"],
        features: [
          "Fetches a Random task from Bored API then fetches a related Photo from Unsplash API.",
          "Preloading, loading and status states are managed based on async functions.",
          "Implemented Netlify Serverless Functions (Lambda) to handle the backend.",
          "All API calls are made from the backend functions, keeping API credentials secret.",
        ],
      },
      // {
      //   title: null,
      //   shortDescription: null,
      //   link: null,
      //   repo: null,
      //   builtWith: [],
      //   features: [],
      // },
    ],
    experiences: [
      {
        position:
          "E-commerce Operations Associate, Inventory Management Associate",
        company: "Wadi Groceries, Carrefour",
        location: "Riyadh, Saudiarabia",
        dateFrom: "APR 2018",
        dateTo: "MAR 2019",
        skills: [
          "Communication skills",
          "Organizational skills",
          "Ability to work independently and as part of a team",
          "Attention to detail",
          "Problem-solving skills",
          "Technical skills (MS Excel, Ecommerce Dashboard)",
          "Ability to learn new technologies quickly",
        ],
        responsibilities: [
          "Pocessed on average 50-70 online orders each day accurately and efficiently",
          "Assembled and packaged orders for shipping",
          "After promotion I used to update shop database using MS Excel and their ecommerce online console inorder to maintain inventory records",
          "Troubleshooted technical problems",
          "Thrived to stay up-to-date on the latest ecommerce technologies",
        ],
      },
      // {
      //   position: "Freelance Food Delivery Driver",
      //   company: "",
      //   location: "",
      //   dateFrom: "JUNE 2019",
      //   dateTo: "OCT 2019",
      //   skills: ["Time management", "Customer service", "Communication"],
      //   responsibilities: [
      //     "Receive orders on phone",
      //     "Pick up and deliver food on time",
      //     "Maintain a clean and organized car",
      //     "Follow safety procedures",
      //     "Communicate with customers regarding order status",
      //   ],
      // },
      {
        position: "Returns Processor",
        company: "JollyChik Warehouse SA",
        location: "Riyadh, Saudiarabia",
        dateFrom: "FEB 2018",
        dateTo: "APR 2018",
        skills: [
          "Attention to detail",
          "Accuracy",
          "Ability to work independently and as part of a team",
          "Technical skills (scanning, data entry)",
        ],
        responsibilities: [
          "I scanned returned items and updated inventory records (average of 600-700 items per day)",
          "Inspected returned items for damage",
          "Processed returns according to company policy",
          "Kept the warehouse clean and organized",
        ],
      },
      // {
      //   position: "Flyer Distributor (Part time)",
      //   company: "Moneygram Financial Service",
      //   location: "Riyadh, Saudiarabia",
      //   dateFrom: "JUL 2017",
      //   dateTo: "FEB 2018",
      //   skills: [
      //     "Persuasion skills",
      //     "Communication skills (verbal and written)",
      //     "Interpersonal skills",
      //     "Flexibility",
      //   ],
      //   responsibilities: [
      //     "Distributed flyers to targeted areas generating on average of 150-200 leads per day.",
      //     "Built relationships with potential leads",
      //     "I convinced and persuaded leads into trying the company's services",
      //     "I had to maintain a positive attitude and demeanor to win over potential customers",
      //   ],
      // },
    ],
    educations: [
      {
        title: "Self-taught MERN Stack Developer",
        institute: null,
        location: "Bangladesh",
        dateFrom: "2023",
        dateTo: "Present",
      },
      {
        title: "Fullstack Web Development",
        institute: "Shikhbe Shobai",
        location: "Bangladesh",
        dateFrom: "2020",
        dateTo: "2021",
      },
      {
        title: "Higher School Certificate",
        institute: "Bangladesh International School & College",
        location: "Saudiarabia",
        dateFrom: "2014",
        dateTo: "2015",
      },
      {
        title: "Secondary School Certificate",
        institute: "Bangladesh International School & College",
        location: "Saudiarabia",
        dateFrom: "2011",
        dateTo: "2013",
      },
      {
        title: "Junior School Certificate",
        institute: "Bangladesh International School & College",
        location: "Saudiarabia",
        dateFrom: "2009",
        dateTo: "2010",
      },
    ],
  },
}

export default resume
